# Generated by Django 5.0.1 on 2024-02-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_clientaccount_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
