# Generated by Django 5.0.1 on 2024-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_clientaccount_is_admin_alter_clientaccount_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='profile_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads'),
        ),
    ]
